# This is a basic workflow that is manually triggered

name: CI

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
    - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman:latest
      volumes: 
        - test:/etc/newman
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@main
      
    # # INstall Node on the runner
    # - name: Install Node
    #   uses: actions/setup-node@v1
    #   with: 
    #     node-version: '12.x'
    
    # # Install the newman command line utility and also install the html extra reporter
    # - name: Install newman
    #   run: |
    #    npm install -g newman

    # # Run the POSTMAN collection
    # - name: Run POSTMAN collection
    #   run: |
    #    newman run ./test/HttpbinForNewman.json -r cli

    # Run the docker of newman
    - name: Docker for newman
      run: |
        run "HttpbinForNewman.json" --reporters="cli"